### ISSUE TITLE
Standardize style process

### ISSUE THREAD

**Issue by webelaine** [a8cteam51/build-processes-demo#16]
I'd like to suggest using `postcss` for all stylesheets. That way everyone can use SCSS or CSS syntax, whichever they prefer, which simplifies the build process a bit. If we include `postcss-generate-asset-php` it also takes care of versioning and dependencies (#14). If we go this route, we could have a single `/theme/assets/styles/` folder instead of separate `css` and `scss` folders.

**Comment by ahegyes** [comment]
Thank you for suggesting this @webelaine! I think I speak for many people when I say that I didn't even know that `scss` files can be built using `postcss`!

I opened PR #26 the other day which adds `postcss` as part of the build process we currently have. Building on top of it, PR #27 replaces `sass` entirely and builds the `scss` files using `postcss` as you suggested. It would be great if you could take a look over the `packages.json` file of that PR and confirm that this is what you had in mind :) 

I personally like that the build process still uses `sass` in the background and that the NPM script commands become much shorter by doing it this way. The exact same things can also be seen as a negative though (usage of `sass` is hidden in the background basically).

I think we'll need to ask more developers what their preferred approach is before recommending one way over the other :) 

> If we include postcss-generate-asset-php it also takes care of versioning and dependencies (https://github.com/a8cteam51/build-processes-demo/issues/14)

I was excited about that the very first time I read your comment. I am personally still leaning toward `filemtime` because it would work even if, in case of emergency, the CSS files would be modified directly in production. The counter-argument would be that modifying the PHP file as well with some random string is not that big of a deal in order to ensure cache-busting.

As @georgestephanis pointed out in Slack during the last meeting of the task force, using a PHP file can have performance benefits since it can be cached in OPCache. But with the HTML sitting in a cached layer itself and with SSDs being used nowadays, the few extra calls to `filemtime` shouldn't be much of a concern.

---

Overall, thank you for bringing up these two discussion points! They really bring a lot of value to the project and the end result, whichever it will be, will be better thanks to the discussions on this issue!

**Comment by webelaine** [comment]
I'm glad postcss's SASS processing and versioning are helpful. We (Happy Prime) have certainly found them very useful in our projects!

I personally struggle to justify a choice because of on-the-fly changes that might need to be made. For CSS in particular, many sites have an Additional CSS section in the Customizer where this type of change can be made. It also feels like CSS could fairly quickly be deployed as needed, and if run through the standard GitHub workflow, the build process would generate the version asset. And as you mentioned, one could modify the asset file directly if absolutely necessary. For that reason, I think `postcss-generate-asset-php` is a good way to go (and it also handles dependencies, in addition to versioning).

**Comment by jeremyfelt** [comment]
> I am personally still leaning toward `filemtime`

+1 for this. We were excited about `postcss-generate-asset-php` for a while, and have added it to so many projects, but it becomes a real pain when multiple style branches are open at the same time that were created from `trunk` but are open on `develop`. The asset files generate regular conflicts that always take more than a minute to unwind because of the mixed branch mergings.

As long as built files are included in the repository, then I think `filemtime` does the trick well.

**Comment by tommusrhodus** [comment]
> The asset files generate regular conflicts that always take more than a minute to unwind because of the mixed branch mergings.

This decided it for us. @ahegyes has developed a hybrid system in #23 for handling these that will allow you to use the method of your choosing. We'll be merging this soon.

Closing this discussion since we've reached a good method of handling these, please ping or re-open if you want to discuss further :)
