### ISSUE TITLE
SCSS files in CSS folder

### ISSUE THREAD

**Issue by webelaine** [a8cteam51/build-processes-demo#17]
- The `theme/assets/css/src` folder contains SCSS files.
- Are the cart and checkout files in this folder included by default, or are they just examples? Not all sites have a cart.

**Comment by otakupahp** [comment]
I agree, these files must be moved to SCSS folder (which should be names sass)

**Comment by ahegyes** [comment]
The repo contains examples of doing all sorts of things that won't apply to every project. This is an example thereof. 

The files under `assets/scss` (which we agreed in the task force meeting today should be renamed to `sass`) are meant to contain SASS files for compiling the theme's `style.css`. The files under `assets/css` are meant to be single-purpose CSS files to be enqueued on certain pages, or when a given block is present on the page (using the conditional `has_block`) or any other conditional and well-scoped scenario.

Ultimately, since these files are likely to be much smaller in scope, the `assets/css` folder might contain a few small CSS files directly. Or if one wants to use SASS, we recommend the current structure of a `src` and a `build` folder to follow the same structure as webpack (used for the Gutenberg blocks and for compiling JS/TS files) for consistency.

**Comment by ahegyes** [comment]
This has been answered more in-depth in these two README FAQs:

* [What's with the build and src folders for the js and css folders?](https://github.com/a8cteam51/build-processes-demo#whats-with-the-build-and-src-folders-for-the-js-and-css-folders)
* [Do I need to use everything in this demo project?](https://github.com/a8cteam51/build-processes-demo#do-i-need-to-use-everything-in-this-demo-project)
