### ISSUE TITLE
WC opt-in

### ISSUE THREAD

**Issue by webelaine** [a8cteam51/build-processes-demo#19]
The WooCommerce Usage auto-opt-in feels a little awkward. I can see why it would be desirable to always opt into usage tracking for sites that use Woo, but not all sites do. Maybe this could be a recommended plugin but not always bundled?

**Comment by georgestephanis** [comment]
Previous discussion on the topic:

https://github.com/Automattic/team51-cli/issues/102#issuecomment-1224866715

**Comment by ahegyes** [comment]
Per the discussion linked by @georgestephanis above, I think the submodule should stay in the default project since we can never be sure if a website will include the plugin later on or not. Moreover, the naming of the repo isn't very accurate anymore since it also opts into Sensei tracking (and might be enhanced in the future again).

Ultimately, this project is meant to represent a default and an example for all sorts of scenarios that might not apply to all websites. If it's painfully clear that the WC opt-in submodule will never, ever apply to a site, then it should be fine to remove for said project :)

**Comment by webelaine** [comment]
I don't know if there's a way to add options for a default project, but something similar to the Foundation framework, where you can select just the components you need and it bundles those for you to use on your project, would be extra awesome. I can understand how if there is no similar Git functionality, all the common components would need to be included.

**Comment by ahegyes** [comment]
I've added the reasoning for this [in the README](https://github.com/a8cteam51/build-processes-demo#can-i-remove-the-wc-usage-tracking-auto-opt-in-git-module). For now, the module should remain auto-included as long as the partner doesn't explicitly ask us against it. 

> I don't know if there's a way to add options for a default project, but something similar to the Foundation framework, where you can select just the components you need and it bundles those for you to use on your project, would be extra awesome. I can understand how if there is no similar Git functionality, all the common components would need to be included.

I agree but it's kind of out-of-scope for this project 😅 If this becomes popular enough though, I don't see why that couldn't be included in the future 😄
