### ISSUE TITLE
Consider allowing short array syntax in the default PHPCS configuration

### ISSUE THREAD

**Issue by jeremyfelt** [a8cteam51/build-processes-demo#38]
### Description

👋🏻 We've (Happy Prime) been using short array syntax on our projects for a bit now and have enjoyed it, especially when writing so much JS alongside PHP. If you all are okay with it, we'd like to continue, but we're also okay switching back to long array syntax for consistency if needed.

The current WPCS 2.0 config is this:

```
<!-- WordPress should allow short array syntax. -->
<rule ref="Generic.Arrays.DisallowShortArraySyntax">
	<exclude name="Generic.Arrays.DisallowShortArraySyntax.Found"/>
</rule>
```

In WPCS `dev-develop`, I believe Generic changes to Universal.

**Comment by tommusrhodus** [comment]
Hey @jeremyfelt 👋 

Since the [WordPress handbook explicitly requires long array syntax](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays) we're going to say that we're requiring long array syntax also.

The good news is that PHPCBF should convert this automatically if you have any snippets etc. that currently use short syntax, so hopefully this doesn't cost you much in terms of time.

If the WordPress standards change in the future, we will allow short syntax also.

Closing this but please ping me if you want to discuss further! 😄
