### ISSUE TITLE
Consider default PostCSS packages for a non-SASS workflow

### ISSUE THREAD

**Issue by jeremyfelt** [a8cteam51/build-processes-demo#39]
### Description

We (Happy Prime) default to CSS only rather than SASS. A small handful of PostCSS plugins make it possible to write CSS in a SASSsy (😎) way while staying close to pure CSS. Once custom CSS variables became supported everywhere, then the only real SASS need for us was nesting, which `postcss-nested` provides.

Our current workflow is a `wp-content/{theme}/css/` directory that builds to `wp-content/{theme}/style.css` and `wp-content/{theme}/editor-style.css`. This is setup so that more focused stylesheets could be built for single/archive/etc... views, though that generally hasn't been necessary.

I've updated the Cool Hunting repo to show an example of how this would work for us while still using the files from this repo:

```
plugins: [
	...( isSass ? [ require( '@csstools/postcss-sass' ) ] : [
		require( 'postcss-advanced-variables' ),
		require( 'postcss-preset-env' ),
		require( 'postcss-nested' ),
		require( 'postcss-custom-media' ),
	] ),
	...postcssPlugins,
]
```

The caveat for all of this is that we're happy to switch to the SASS workflow provided by this repository if that makes your jobs easier. 😄

**Comment by ahegyes** [comment]
Hi @jeremyfelt! 

As a rule of thumb, the default should always be SASS via SCSS files. However, we've agreed to your suggested variation and trust that this flexibility will be used responsibly, i.e. not in a way that will make maintenance a nightmare 😄   

To be clear, you should still use the repo's example folder structure, but it's fine to use `postcss` plugins for "compiling" CSS instead of SCSS files.
